### ISSUE TITLE
[suggestion] Support for additional authorization Mojang  APIs

### ISSUE THREAD

**Issue by xpiREC** [kyngs/LibrePremium#13]
There is currently one Mojang API authorization system supported, and it has request execution restrictions.
I propose to add randomness to select other intermediary rest api interfaces, of course it would be nice to give a choice

Which I know of:
- https://api.minetools.eu/uuid
- https://mcapi.cloudprotected.net
- https://api.ashcon.app/mojang/v2/user

**Comment by kyngs** [comment]
The issue is, that I need one that is always in sync with Mojang. Can you confirm that any of these accomplishes it?

**Comment by LouissXI** [comment]
Yes they are well synchronized with the Mojang API

**Comment by kyngs** [comment]
For example, minetools does cache the request.

**Comment by LouissXI** [comment]
What you could do is add the possibility to add other URLs in the config but specify that they must be synchronized with the Mojang API, so that the servers that need them can use their own API etc

**Comment by kyngs** [comment]
It's not just about changing the URL, these APIs use different schemas. The cloudprotected one does look promising tho.

**Comment by LouissXI** [comment]
That's nice, please keep us updated to what are your plans for this

**Comment by kyngs** [comment]
Implemented CloudProtected in the latest version
