### ISSUE TITLE
[Feature Request]Request to add a Feature to restrict same IP registrations.

### ISSUE THREAD

**Issue by chundongg** [kyngs/LibrePremium#18]
Please restrict the number of same IP registrations to simply restrict unnecessary account registrations.
The config in the proxy writen like 'Relogin: 3' and 'Regreg: 3' ?

**Comment by kyngs** [comment]
I extremely suggest you not do this, because ISPs tend to put several households (in some cases even hundreds of them) under the same IP. LibrePremium won't support such restriction, because there are already several plugins available to do this.
