### ISSUE TITLE
The supplied pass-through server is not configured in the proxy configuration!

### ISSUE THREAD

**Issue by A1Panda** [kyngs/LibrePremium#20]
[LibrePremium]: !! THIS IS MOST LIKELY NOT AN ERROR CAUSED BY LIBREPREMIUM !!
[20:13:32 ERROR] [LibrePremium]: !!The configuration is corrupted, please look below for further clues. If you are clueless, delete the conf
ig and a new one will be created for you. Cause: CorruptedConfigurationException: The supplied pass-through server is not configured in the
proxy configuration

**Comment by kyngs** [comment]
The pass-through server you supplied isn't configured in the proxy.

**Comment by kyngs** [comment]
cannot reproduce
