### ISSUE TITLE
Register: "The provided email address is invalid"

### ISSUE THREAD

**Issue by aotahal** [kyngs/LibrePremium#21]
Hello, I have problem, when I try to register with /register <passwd> <passwd>, it returns me a message: "The provided email address is invalid". 

Screenshots:
![image](https://user-images.githubusercontent.com/96112160/187475397-ed3c639b-815f-4668-8c9a-38a542e49f0d.png)

Thank you for answering!

**Comment by kyngs** [comment]
I'm not sure how that's possible, because librepremium does not operate with e-mails at all, perhaps you are using some other plugin?
