### ISSUE TITLE
[Suggestion] Option to disable fallback completely

### ISSUE THREAD

**Issue by Shad0wolf0** [kyngs/LibrePremium#22]
I have a few problems with your fallback option. If set to true, kicking players from the lobby will not see a disconnect screen. This is a bug. They're still connected to proxy but not in the world. It gives the 'You are already connected to this server!' to them. At the same time they're still in the lobby world, but unable to do anything serious, like the BungeeReconnect plugin, except it doesn't reconnect the player. Now if I set it to false, that problem is solved but interferes with the RedirectPlus plugin. RP is supposed to send them back to the lobby when getting kicked or shut down from a survival server, and instead of RP redirecting them to the lobby, LibrePremiuum shows the player a disconnect screen, because it handles it differently I assume.

Edit: I want to add, if set to true, I have the RP plugin setup to bottom-kick them from the lobby.

**Comment by DoreK333** [comment]
I have the same problem with the fallback option. If the lobby is down, LibrePremium tries to connect to it anyway, and the player only sees "Connecting to server..." instead of the can't connect message.

I think the bug is that LibrePremium is looping attempts to connect to the lobby instead of kicking the player from the proxy after a failed connection.

**Comment by cupang-afk** [comment]
i agree with this.
i would like to use RedirectPlus to redirect player when the server is offline/shutdown or player got kicked to my fallback limbo server 

im using 0.12.0 right now, the kick redirect work well but the shutdown aren't, it only shows `You are already connected to this server` on chat and leads to a `Read Time Out` error message

or if you wont, please add something like `fallback server list` just like the limbo one, for example:
```
fallback=[
    fallback1,
    fallback2
]
```

**Comment by kyngs** [comment]
Gonna take a look at it when I'll have time

**Comment by Misterio77** [comment]
Hey folks. Here's a patch that should you out: https://github.com/kyngs/LibrePremium/pull/38

**Comment by kyngs** [comment]
Should be fixed in https://github.com/kyngs/LibrePremium/commit/565b6f106843d97f2d57a74a52c65f933ccac14f

**Comment by Shad0wolf0** [comment]
It works! Thank you so much for fixing it! This truly is the best free proxy auth plugin
