### ISSUE TITLE
Feature Request: Forced Hosts

### ISSUE THREAD

**Issue by Seercat3160** [kyngs/LibrePremium#24]
I believe that one should be able to setup Forced Hosts for the pass-through servers, similarly to in Velocity config.

I run multiple servers accessed by URLs, but I can't currently do that while using this plugin.

This would involve being able to override the passthrough list in the config based on what domain the user is connecting from.

**Comment by DoreK333** [comment]
i need it too

**Comment by kyngs** [comment]
@DoreK333 @Seercat3160 Would one of you be able to test it if I were to attach the binary here? (I, unfortunately, do not have the setup to try it. Do you both use bungee?)

**Comment by DoreK333** [comment]
Yes, I can test. I'm using Velocity.

**Comment by kyngs** [comment]
> Yes, I can test. I'm using Velocity. @kyngs

OK, perfect.
You can either compile the code yourself or use the binary attached. [LibrePremium.zip](https://github.com/kyngs/LibrePremium/files/9913370/LibrePremium.zip)

Please consult the wiki page on how to configure it. In case there are some questions, feel free to ask. https://github.com/kyngs/LibrePremium/wiki/Configuring-Servers

@Seercat3160 If you use Bungee, please try it too, so I can verify whether it works on bungee as well.

**Comment by DoreK333** [comment]
Unfortunetely, not work in my case.

Config:
```
    root=[
        lobby
    ],
	bud§reverial§net=[
        bud
    ]
```

If I try to connect to bud.reverial.net I am still redirected to the lobby server instead of bud.

**Comment by kyngs** [comment]
> Unfortunately, not work in my case.
> 
> Config:
> 
> ```
>     root=[
>         lobby
>     ],
> 	bud§reverial§net=[
>         bud
>     ]
> ```
> 
> If I try to connect to bud.reverial.net I am still redirected to the lobby server instead of bud.

Hmm, can you please try this version, enable debug mode, try to connect, and send the logs?
[LibrePremium.zip](https://github.com/kyngs/LibrePremium/files/9913485/LibrePremium.zip)

**Comment by DoreK333** [comment]
Ohh, ok. I see:
[20:38:15 INFO] [librepremium]: [DEBUG] Virtual host for player DoreK is play.reverial.net/<unresolved>:25565

I'm using SRV record, so the plugin probably doesn't support SRV yet.

**Comment by kyngs** [comment]
> Ohh, ok. I see: `[20:38:15 INFO] [librepremium]: [DEBUG] Virtual host for player DoreK is play.reverial.net/<unresolved>:25565`
> 
> I'm using SRV record, so the plugin probably doesn't support SRV yet.

Can you triple-check that you are indeed connecting to bud.reverial.net? Velocity reports that you are connecting to play.reverial.net.

**Comment by DoreK333** [comment]
Yes, this is due to the SRV record:
![image](https://user-images.githubusercontent.com/11007700/199324087-f817472a-df60-422a-885f-17f4965523a8.png)

The important thing is that another plugin (MiniMOTD) has no problem with that.

**Comment by kyngs** [comment]
> Yes, this is due to the SRV record: ![image](https://user-images.githubusercontent.com/11007700/199324087-f817472a-df60-422a-885f-17f4965523a8.png)
> 
> The important thing is that another plugin (MiniMOTD) has no problem with that.

That is very weird, looking at MiniMOTD's source, it appears that we use the very same way. I will most likely file an issue on Velocity's github.

**Comment by DoreK333** [comment]
Okay, so far I changed the record from SRV to A - everything works fine. Hope SRV will be work soon :p

**Comment by kyngs** [comment]
> Okay, so far I changed the record from SRV to A - everything works fine. Hope SRV will be work soon :p

Okay, thanks for your cooperation!

**Comment by kyngs** [comment]
@DoreK333 https://github.com/PaperMC/Velocity/issues/885#issuecomment-1299148834

**Comment by kyngs** [comment]
@Seercat3160 Can you please try this out?

**Comment by kyngs** [comment]
Gonna hope that it works.

**Comment by Seercat3160** [comment]
Yes, thank you! I'm on Velocity as well though so that's to be expected as it worked for the other person.
