### ISSUE TITLE
Suggestion: More APIs support

### ISSUE THREAD

**Issue by DoreK333** [kyngs/LibrePremium#27]
An additional/another option to avoid the Mojang API limit is support for other APIs.
So far I have used the DynamicBungeeAuth plugin, which used the following API:

Mojang, CloudProtected (https://mcapi.cloudprotected.net/), MineTools (https://api.minetools.eu)/
I suspect there are also more APIs that could be used.

The order of API operation would be selected in the plugin configuration. If the first one does not work, the next one will be used, etc.

**Comment by kyngs** [comment]
CloudProtected cannot be used due to its capitalization issues. Might consider MineTools. See my answer on #26

**Comment by xpiREC** [comment]
Consider using https://playerdb.co maintenance is using cloudflare worker, steam and nodecraft servers - they have a cache, but it works, on the principle of get and then in the background check for updates, so that even in case of failure we have access and speed up the authorization process.

**Comment by kyngs** [comment]
> Consider using https://playerdb.co maintenance is using cloudflare worker, steam and nodecraft servers - they have a cache, but it works, on the principle of get and then in the background check for updates, so that even in case of failure we have access and speed up the authorization process.

Looks nice, thanks. Definitely will implement
