### ISSUE TITLE
Requirement to /login after a failure of authorization servers

### ISSUE THREAD

**Issue by DoreK333** [kyngs/LibrePremium#29]
During the last failure of Mojang's authorization servers, when I tried to enter the server, the "uuid premium" value in the database became null, so when I tried to enter the server the next day, the plugin asked me to log in using /login command (even though I am premium player).

This probably happened after many attempts to enter the Velocity server as I was previously kicked out because the (Mojang) servers are down.

**Comment by kyngs** [comment]
I am aware of this being buggy when Mojang is down, but I don't really know how to debug this. The only option would be to have debug mode on, wait for another Mojang failure, and send me the logs for the players whose premium UUID got reset. Having debug mode on will obviously spam your console a bit.

**Comment by kyngs** [comment]
> I am aware of this being buggy when Mojang is down, but I don't really know how to debug this. The only option would be to have debug mode on, wait for another Mojang failure, and send me the logs for the players whose premium UUID got reset. Having debug mode on will obviously spam your console a bit.

@DoreK333 will you do this?

**Comment by DoreK333** [comment]
Yes, but so far I have not been able to reproduce this bug

**Comment by kyngs** [comment]
You can only really reproduce it when mojang servers are down

**Comment by Bartek200219** [comment]
> You can only really reproduce it when mojang servers are down

You can just temporarily ban your self by spamming f5 on minecraft website or just block connection in your own firewall to check this problem

**Comment by kyngs** [comment]
> > You can only really reproduce it when mojang servers are down
> 
> You can just temporarily ban your self by spamming f5 on minecraft website or just block connection in your own firewall to check this problem 

Unfortunately no, because the plugin will fall back to ashcon API. Unfortunately I don't know how ashcon API behaves when Mojang API is down.

**Comment by kyngs** [comment]
Well, the site does not shut down when Mojang does. I have no idea whether it reports an error or cached data.

**Comment by Bartek200219** [comment]
I wanted to say that it's unlikely that it cashes anything
