### ISSUE TITLE
configuration is corrupted

### ISSUE THREAD

**Issue by HunterZomb** [kyngs/LibrePremium#3]
Hey, I've installed the plugin on my bungeecord added the database credentials but it says Cause: CorruptedConfigurationException: Crypto provider not found in the console, i checked the config and its set to BCrypt2A

Its set to BCrypt2A but still everytime i start it says "Cause: CorruptedConfigurationException: Crypto provider not found", Please Fix 😄

**Comment by kyngs** [comment]
Hi, it looks like I've messed up the configuration comment a bit, it should be BCrypt-2A, not BCrypt2A. Gonna fix it ASAP.

**Comment by HunterZomb** [comment]
Thx for the instant response!!! 😮

**Comment by kyngs** [comment]
> Ive also found another issue regarding migration, should i make another issue report or its fine if ill report it here?

If possible, make another issue.
