### ISSUE TITLE
2fa code bug

### ISSUE THREAD

**Issue by KikyoC** [kyngs/LibrePremium#32]
Hii again,

I got this issue: https://i.badlion.net/2PyTJ8ntdptrnjV3UwiZGW.png

I got that when I do /2fa

Thanks

**Comment by kyngs** [comment]
Are you using NanoLimbo?

**Comment by KikyoC** [comment]
Yes im using NanoLimbo. Nothing appear ine the proxy

**Comment by KikyoC** [comment]
The creator of NanoLimbo saw that: "
Maybe this happens because player not receive all required packets, only minimal amount to stay player connected. But i'm not completely sure, i thought if proxy sends these packets to player, all should be okay."

**Comment by kyngs** [comment]
Gonna close this, see https://github.com/Nan1t/NanoLimbo/issues/49 for further updates.
