### ISSUE TITLE
JPremium feature question

### ISSUE THREAD

**Issue by JRGrim** [kyngs/LibrePremium#33]
I want to make you a question, the token feature from JPremium sounds good on paper, LibrePremium doesn't have this feature, It looks quite necessary, how do you prevent this from happening in your plugin?

**Comment by kyngs** [comment]
Sorry, but what is the token feature?

**Comment by JRGrim** [comment]
# The access token which is used to verify connections on your Spigot servers whether connections come from your BungeeCord.
# Please enter fully random unique value! Not: 'your-server-name-jpremium'!
# The same token you have to enter on all your Spigot servers.

You place a token in your configuration and the backend server's configuration, similar how Bungeeguard works.

**Comment by kyngs** [comment]
> ```
> The access token which is used to verify connections on your Spigot servers whether connections come from your BungeeCord.
> Please enter fully random unique value! Not: 'your-server-name-jpremium'!
> The same token you have to enter on all your Spigot servers.
> accessToken: 'tokenhere'
> ```
> 
> You place a token in your configuration and the backend server's configuration, similar how Bungeeguard works.

It would be absolutely redundant for an authentication plugin to attempt to implement this, because:
BungeeCord has BungeeGuard
Velocity has built-in modern forwarding
