### ISSUE TITLE
[suggestion] add prefix for crack players

### ISSUE THREAD

**Issue by gamer50082** [kyngs/LibrePremium#39]
add a configurable prefix for crack players

check player with mojang/microsoft auth first and if given a 403 or a reject error code then mark player as crack

**Comment by kyngs** [comment]
Won't implement, you can do this via the API

**Comment by gamer50082** [comment]
how

**Comment by gamer50082** [comment]
and is there any availble online?

**Comment by gamer50082** [comment]
but will prem retain its uuid and crack gets a random gen one
