### ISSUE TITLE
Migration from JPremium

### ISSUE THREAD

**Issue by HunterZomb** [kyngs/LibrePremium#4]
Hey, while i was migrating i got this error, i was migrating from jpremium

17:20:58 [INFO] [LibrePremium] Connected to the OLD database
17:20:58 [INFO] HikariPool-2 - Start completed.
17:20:58 [INFO] [LibrePremium] Starting data conversion... This may take a while!
17:20:58 [INFO] HikariPool-2 - Shutdown initiated...
17:21:01 [INFO] HikariPool-2 - Shutdown completed.
17:21:01 [SEVERE] [LibrePremium] An unexpected exception occurred while performing database migration, aborting migration
17:21:01 [SEVERE] java.lang.NullPointerException: Cannot invoke "java.util.function.Function.apply(Object)" because "this.exceptionHandler" is null
17:21:01 [SEVERE]     at xyz.kyngs.easydb.EasyDB.handleException(EasyDB.java:78)
17:21:01 [SEVERE]     at xyz.kyngs.easydb.EasyDB.runTask(EasyDB.java:70)
17:21:01 [SEVERE]     at xyz.kyngs.easydb.EasyDB.runFunctionSync(EasyDB.java:112)
17:21:01 [SEVERE]     at xyz.kyngs.librepremium.common.migrate.JPremiumReadProvider.getAllUsers(JPremiumReadProvider.java:39)
17:21:01 [SEVERE]     at xyz.kyngs.librepremium.common.AuthenticLibrePremium.migrate(AuthenticLibrePremium.java:322)
17:21:01 [SEVERE]     at xyz.kyngs.librepremium.common.AuthenticLibrePremium.checkAndMigrate(AuthenticLibrePremium.java:211)
17:21:01 [SEVERE]     at xyz.kyngs.librepremium.common.AuthenticLibrePremium.enable(AuthenticLibrePremium.java:156)
17:21:01 [SEVERE]     at xyz.kyngs.librepremium.bungeecord.BungeeCordLibrePremium.makeEnabled(BungeeCordLibrePremium.java:34)
17:21:01 [SEVERE]     at xyz.kyngs.librepremium.bungeecord.BungeeCordPlugin.onEnable(BungeeCordPlugin.java:39)
17:21:01 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:265)
17:21:01 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:285)
17:21:01 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
17:21:01 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
17:21:01 [INFO] Enabled plugin LibrePremium version 0.3.1 by kyngs

I Hope this will be fixed soon 😄

**Comment by HunterZomb** [comment]
sure

**Comment by HunterZomb** [comment]
Now it says this:

17:36:10 [INFO] [LibrePremium] Performing migration...
17:36:10 [INFO] [LibrePremium] Connecting to the OLD database...
17:36:10 [INFO] HikariPool-2 - Starting...
17:36:13 [INFO] HikariPool-2 - Added connection xyz.librepremium.lib.mysql.cj.jdbc.ConnectionImpl@345cf395
17:36:13 [INFO] [LibrePremium] Connected to the OLD database
17:36:13 [INFO] HikariPool-2 - Start completed.
17:36:13 [INFO] [LibrePremium] Starting data conversion... This may take a while!
17:36:14 [INFO] HikariPool-2 - Shutdown initiated...
17:36:16 [INFO] HikariPool-2 - Shutdown completed.
17:36:16 [SEVERE] [LibrePremium] An unexpected exception occurred while performing database migration, aborting migration
17:36:16 [SEVERE] java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-data' at line 1
17:36:16 [SEVERE]     at xyz.kyngs.easydb.EasyDB.throwExceptionAsRuntime(EasyDB.java:83)
17:36:16 [SEVERE]     at xyz.kyngs.easydb.EasyDB.handleException(EasyDB.java:76)
17:36:16 [SEVERE]     at xyz.kyngs.easydb.EasyDB.runTask(EasyDB.java:68)
17:36:16 [SEVERE]     at xyz.kyngs.easydb.EasyDB.runFunctionSync(EasyDB.java:110)
17:36:16 [SEVERE]     at xyz.kyngs.librepremium.common.migrate.JPremiumReadProvider.getAllUsers(JPremiumReadProvider.java:39)
17:36:16 [SEVERE]     at xyz.kyngs.librepremium.common.AuthenticLibrePremium.migrate(AuthenticLibrePremium.java:326)
17:36:16 [SEVERE]     at xyz.kyngs.librepremium.common.AuthenticLibrePremium.checkAndMigrate(AuthenticLibrePremium.java:215)
17:36:16 [SEVERE]     at xyz.kyngs.librepremium.common.AuthenticLibrePremium.enable(AuthenticLibrePremium.java:159)
17:36:16 [SEVERE]     at xyz.kyngs.librepremium.bungeecord.BungeeCordLibrePremium.makeEnabled(BungeeCordLibrePremium.java:34)
17:36:16 [SEVERE]     at xyz.kyngs.librepremium.bungeecord.BungeeCordPlugin.onEnable(BungeeCordPlugin.java:39)
17:36:16 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:265)
17:36:16 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:285)
17:36:16 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
17:36:16 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
17:36:16 [SEVERE] Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-data' at line 1
17:36:16 [SEVERE]     at xyz.librepremium.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
17:36:16 [SEVERE]     at xyz.librepremium.lib.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
17:36:16 [SEVERE]     at xyz.librepremium.lib.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
17:36:16 [SEVERE]     at xyz.librepremium.lib.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009)
17:36:16 [SEVERE]     at xyz.librepremium.lib.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
17:36:16 [SEVERE]     at xyz.librepremium.lib.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
17:36:16 [SEVERE]     at xyz.kyngs.librepremium.common.migrate.JPremiumReadProvider.lambda$getAllUsers$0(JPremiumReadProvider.java:42)
17:36:16 [SEVERE]     at xyz.kyngs.easydb.provider.mysql.MySQL.runTask(MySQL.java:44)
17:36:16 [SEVERE]     at xyz.kyngs.easydb.EasyDB.runTask(EasyDB.java:52)
17:36:16 [SEVERE]     ... 11 more
17:36:16 [INFO] Enabled plugin LibrePremium version 0.3.4-SNAPSHOT by kyngs
17:36:16 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.18-R0.1-SNAPSHOT:a17d8f8:1634 by SpigotMC

**Comment by kyngs** [comment]
Can you please show me the migration part of the config? (Censor out DB credentials)

**Comment by HunterZomb** [comment]
Yeah sure

**Comment by HunterZomb** [comment]
# Kick the player, if the password is wrong.
kick-on-wrong-password=false
# The limbo, players should be sent to, when not authenticated.
limbo=Lobby
migration {
    old-database {
        # The name of the old database.
        database=b5dhe*****
        # The host of the old database.
        host="b5dhe*****-mysql.services.clever-cloud.com"
        # The password of the old database.
        password=ib*************
        # The port of the old database.
        port=3306
        # The table of the old database.
        table=user-data
        # The user of the old database.
        user=u1**********
    }
    # Migrate the database on the next startup.
    on-next-startup=true
    # The type of the migration.
    # Available Types: JPremium
    type=JPremium
}
# Sets which method should be used for creating fixed UUID when a new player is created.
# See the wiki for further information: https://github.com/kyngs/LibrePremium/wiki/UUID-Creators
# Available Creators:

**Comment by kyngs** [comment]
Oh, it looks like MySQL is a bit confused by your table name, can you try it again with the version attached?
[Extract Me.zip](https://github.com/kyngs/LibrePremium/files/8411981/Extract.Me.zip)

**Comment by HunterZomb** [comment]
sure

**Comment by HunterZomb** [comment]
Now it says:

```
17:48:25 [SEVERE] [LibrePremium] An unexpected exception occurred while performing database migration, aborting migration
17:48:25 [SEVERE] java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: Table 'b5dhe7bhd0mwonlv3hvl.user-data' doesn't exist
17:48:25 [SEVERE]     at xyz.kyngs.easydb.EasyDB.throwExceptionAsRuntime(EasyDB.java:83)
17:48:25 [SEVERE]     at xyz.kyngs.easydb.EasyDB.handleException(EasyDB.java:76)
17:48:25 [SEVERE]     at xyz.kyngs.easydb.EasyDB.runTask(EasyDB.java:68)
17:48:25 [SEVERE]     at xyz.kyngs.easydb.EasyDB.runFunctionSync(EasyDB.java:110)
17:48:25 [SEVERE]     at xyz.kyngs.librepremium.common.migrate.JPremiumReadProvider.getAllUsers(JPremiumReadProvider.java:39)
17:48:25 [SEVERE]     at xyz.kyngs.librepremium.common.AuthenticLibrePremium.migrate(AuthenticLibrePremium.java:326)
17:48:25 [SEVERE]     at xyz.kyngs.librepremium.common.AuthenticLibrePremium.checkAndMigrate(AuthenticLibrePremium.java:215)
17:48:25 [SEVERE]     at xyz.kyngs.librepremium.common.AuthenticLibrePremium.enable(AuthenticLibrePremium.java:159)
17:48:25 [SEVERE]     at xyz.kyngs.librepremium.bungeecord.BungeeCordLibrePremium.makeEnabled(BungeeCordLibrePremium.java:34)
17:48:25 [SEVERE]     at xyz.kyngs.librepremium.bungeecord.BungeeCordPlugin.onEnable(BungeeCordPlugin.java:39)
17:48:25 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:265)
17:48:25 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:285)
17:48:25 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
17:48:25 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
17:48:25 [SEVERE] Caused by: java.sql.SQLSyntaxErrorException: Table 'b5dhe7bhd0mwonlv3hvl.user-data' doesn't exist
17:48:25 [SEVERE]     at xyz.librepremium.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
17:48:25 [SEVERE]     at xyz.librepremium.lib.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
17:48:25 [SEVERE]     at xyz.librepremium.lib.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
17:48:25 [SEVERE]     at xyz.librepremium.lib.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009)
17:48:25 [SEVERE]     at xyz.librepremium.lib.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
17:48:25 [SEVERE]     at xyz.librepremium.lib.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
17:48:25 [SEVERE]     at xyz.kyngs.librepremium.common.migrate.JPremiumReadProvider.lambda$getAllUsers$0(JPremiumReadProvider.java:42)
17:48:25 [SEVERE]     at xyz.kyngs.easydb.provider.mysql.MySQL.runTask(MySQL.java:44)
17:48:25 [SEVERE]     at xyz.kyngs.easydb.EasyDB.runTask(EasyDB.java:52)
17:48:25 [SEVERE]     ... 11 more
```

😅

**Comment by kyngs** [comment]
Well then, table 'user-data' does not exist. 
Considering it is the default, perhaps you forgot to fill it out?

**Comment by HunterZomb** [comment]
oh right!

**Comment by HunterZomb** [comment]
im really sorry

**Comment by kyngs** [comment]
Don't worry

**Comment by HunterZomb** [comment]
Yup, its converting now after changing it to `user_profiles`

**Comment by HunterZomb** [comment]
It converted, thank you so much!

**Comment by kyngs** [comment]
:+1: tell me how it ends up

**Comment by kyngs** [comment]
Thanks for your time, enjoy using LibrePremium. If possible, use the version from SpigotMC, not the one I sent you.
