### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by HunterZomb** [kyngs/LibrePremium#5]
Hey, im sorry for disturbing you continuously but is there any chance you can also add sub title support to the plugin? im fine if you do it later 😄

**Comment by kyngs** [comment]
I will add it to the TO-DO list, I'm currently pretty busy, so I will get to it in a few days.

**Comment by HunterZomb** [comment]
no problem! 👍

**Comment by kyngs** [comment]
Hi, this is now a thing with the new release, search for sub-title-login and sub-tile-register in the messages.
