### ISSUE TITLE
Floodgate support

### ISSUE THREAD

**Issue by iVillager** [kyngs/LibrePremium#7]
Hi!
I was wondering if you will add floodgate support in order to let Bedrock players join the server. Jpremium had this feature, we can't move to a new plugin without this support.

**Comment by kyngs** [comment]
> Hi! I was wondering if you will add floodgate support in order to let Bedrock players join the server. Jpremium had this feature, we can't move to a new plugin without this support.

Hi, Floodgate is already implemented, I'm just awaiting testing.
If you want, you can test it too! Download this build https://filetransfer.io/data-package/XUBIVYic#link

If you see a message like "Floodgate detected" at the end of LibrePremium's log, you have set up everything correctly.

**Comment by kyngs** [comment]
Sorry, sent the wrong link, use this one.
https://filetransfer.io/data-package/vSZLVkMR#link

**Comment by kyngs** [comment]
Floodgate is tested and working in the latest version, if you find any issues open a new issue.
