### ISSUE TITLE
Coordinate support for sending to server or world

### ISSUE THREAD

**Issue by cubeyu** [kyngs/LibrePremium#77]
Excuse me, I am running this pluging in with purpur. After the player logs in, the location of the teleportation to the main city world is not the birth point of the world. I have not found a good way to solve it. Fix where to go after teleportation [such as teleportation to the main city], please help me . Hope the author can add the function of teleport x, y, z to the world
such as：
pass-through {
    root=[
        world[10,10,59]Support teleport x, y, z to the server or world
    ]
}

**Comment by kyngs** [comment]
LibreLogin does not influence the location where players spawn unless they're joining for the first time (then, it uses the world spawn). Perhaps you should install a plugin which would put them to the location you want?

**Comment by kyngs** [comment]
OK, can I close this issue?
